### ISSUE TITLE
Errors when using kube2iam with multiple processes

### ISSUE THREAD

**Issue by prcastro** [jtblin/kube2iam#253]
## Problem

When using several Python processes trying to fetch credentials from `kube2iam` through `boto3`, we have the following error:

```
botocore.exceptions.CredentialRetrievalError: Error when retrieving credentials from iam-role: Credential refresh failed, response did not contain: access_key, secret_key, token, expiry_time
```
Each process was trying to read, process and write parquet partitions from S3 using 96 processes.

### The issue is related with kube2iam

The same problem don't occur when using the same number of threads and the same application with the regular metadata service.

### The problem only appears when using multiprocessing

We tried to reproduce the issue with only one process and the problem disappeared. Notice that wee were still using the `multiprocessing.Pool` but limited to 1 process, so the problem seems to be with the parallelism, not with this module.

### The problem doesn't seem related to the CPU or Memory usage of kube2iam

This was our next bet. However, we used prometheus and found that the CPU and memory usage were quite low at the time we had the incident:

![Captura de Tela 2020-01-22 às 11 34 29](https://user-images.githubusercontent.com/1280742/72903069-551b2b80-3d0b-11ea-878e-24c6bf8a71db.png)
![Captura de Tela 2020-01-22 às 11 35 04](https://user-images.githubusercontent.com/1280742/72903089-5ba9a300-3d0b-11ea-95ed-3d27f9f171ec.png)

_The problem occurred between 20:15 and 20:16_

We also took a look at the node where the application was running, and we didn't see CPU or memory pressure. 

### Latency isn't the problem

Next we took a look into latency. And what we found is that the latency of the HTTP calls to kube2iam don't go much above 125ms. Also, in the python Pod we set the timeout to be way above that (and with several retries) using the `AWS_METADATA_SERVICE_TIMEOUT ` and `AWS_METADATA_SERVICE_NUM_ATTEMPTS` env vars.

![Captura de Tela 2020-01-22 às 11 38 00](https://user-images.githubusercontent.com/1280742/72903548-28b3df00-3d0c-11ea-9045-f2ee5fff6221.png)

Even if latency isn't the problem, it is getting lower and lower latency when time passes by. This is explained by a lower count of requests

![Captura de Tela 2020-01-22 às 11 45 41](https://user-images.githubusercontent.com/1280742/72903870-c3acb900-3d0c-11ea-959f-c75b38e06e1b.png)

### Why are the requests dropping?

Looking at the Python application's logs, we see that from time to time we get the following exception:

```
...
2020-01-21 20:10:18,622 botocore.credentials [DEBUG] Credentials need to be refreshed.
2020-01-21 20:10:18,622 botocore.credentials [DEBUG] Credentials need to be refreshed.
2020-01-21 20:10:18,633 botocore.credentials [DEBUG] Retrieved credentials will expire at: 2020-01-21 20:23:39+00:00
2020-01-21 20:10:18,833 botocore.credentials [DEBUG] Credentials need to be refreshed.
2020-01-21 20:10:18,834 botocore.credentials [DEBUG] Credentials need to be refreshed.
2020-01-21 20:10:18,872 botocore.credentials [DEBUG] Retrieved credentials will expire at: 2020-01-21 20:23:39+00:00
2020-01-21 20:10:18,894 botocore.credentials [DEBUG] Credentials need to be refreshed.
2020-01-21 20:10:18,895 botocore.credentials [DEBUG] Credentials need to be refreshed.
2020-01-21 20:10:18,896 botocore.credentials [DEBUG] Credentials need to be refreshed.
2020-01-21 20:10:18,896 botocore.credentials [DEBUG] Credentials need to be refreshed.
2020-01-21 20:10:19,030 botocore.credentials [DEBUG] Retrieved credentials will expire at: 2020-01-21 20:23:39+00:00
2020-01-21 20:10:19,030 botocore.credentials [WARNING] Refreshing temporary credentials failed during advisory refresh period.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/botocore/httpsession.py", line 263, in send
    chunked=self._chunked(request.headers),
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.6/site-packages/botocore/awsrequest.py", line 125, in _send_request
    method, url, body, headers, *args, **kwargs)
  File "/usr/local/lib/python3.6/http/client.py", line 1295, in _send_request
    self.putheader(hdr, value)
  File "/usr/local/lib/python3.6/http/client.py", line 1232, in putheader
    raise ValueError('Invalid header value %r' % (values[i],))
ValueError: Invalid header value b'{"AccessKeyId":"REDACTED","Code":"Success","Expiration":"2020-01-21T20:23:39Z","LastUpdated":"2020-01-21T20:07:39Z","SecretAccessKey":"REDACTED","Token":"REDACTED","Type":"AWS-HMAC"}\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 502, in _protected_refresh
    metadata = self._refresh_using()
  File "/usr/local/lib/python3.6/site-packages/botocore/utils.py", line 398, in retrieve_iam_role_credentials
    role_name = self._get_iam_role(token)
  File "/usr/local/lib/python3.6/site-packages/botocore/utils.py", line 433, in _get_iam_role
    token=token,
  File "/usr/local/lib/python3.6/site-packages/botocore/utils.py", line 339, in _get_request
    response = self._session.send(request.prepare())
  File "/usr/local/lib/python3.6/site-packages/botocore/httpsession.py", line 299, in send
    raise HTTPClientError(error=e)
botocore.exceptions.HTTPClientError: An HTTP Client raised and unhandled exception: Invalid header value b'{"AccessKeyId":"REDACTED","Code":"Success","Expiration":"2020-01-21T20:23:39Z","LastUpdated":"2020-01-21T20:07:39Z","SecretAccessKey":"REDACTED","Token":"REDACTED","Type":"AWS-HMAC"}\n'

2020-01-21T20:10:19+0000 [ForkPoolWorker-44] WARNING botocore.credentials Refreshing temporary credentials failed during advisory refresh period.

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/botocore/httpsession.py", line 263, in send
    chunked=self._chunked(request.headers),
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.6/site-packages/botocore/awsrequest.py", line 125, in _send_request
    method, url, body, headers, *args, **kwargs)
  File "/usr/local/lib/python3.6/http/client.py", line 1295, in _send_request
    self.putheader(hdr, value)
  File "/usr/local/lib/python3.6/http/client.py", line 1232, in putheader
    raise ValueError('Invalid header value %r' % (values[i],))
ValueError: Invalid header value b'{"AccessKeyId":"REDACTED","Code":"Success","Expiration":"2020-01-21T20:23:39Z","LastUpdated":"2020-01-21T20:07:39Z","SecretAccessKey":"REDACTED","Token":"REDACTED","Type":"AWS-HMAC"}\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 502, in _protected_refresh
    metadata = self._refresh_using()
  File "/usr/local/lib/python3.6/site-packages/botocore/utils.py", line 398, in retrieve_iam_role_credentials
    role_name = self._get_iam_role(token)
  File "/usr/local/lib/python3.6/site-packages/botocore/utils.py", line 433, in _get_iam_role
    token=token,
  File "/usr/local/lib/python3.6/site-packages/botocore/utils.py", line 339, in _get_request
    response = self._session.send(request.prepare())
  File "/usr/local/lib/python3.6/site-packages/botocore/httpsession.py", line 299, in send
    raise HTTPClientError(error=e)
botocore.exceptions.HTTPClientError: An HTTP Client raised and unhandled exception: Invalid header value b'{"AccessKeyId":"REDACTED","Code":"Success","Expiration":"2020-01-21T20:23:39Z","LastUpdated":"2020-01-21T20:07:39Z","SecretAccessKey":"REDACTED","Token":"REDACTED","Type":"AWS-HMAC"}\n'

2020-01-21 20:10:19,344 botocore.credentials [DEBUG] Credentials need to be refreshed.
2020-01-21 20:10:19,344 botocore.credentials [DEBUG] Credentials need to be refreshed.
2020-01-21 20:10:19,351 botocore.credentials [DEBUG] Credentials need to be refreshed.
2020-01-21 20:10:19,351 botocore.credentials [DEBUG] Retrieved credentials will expire at: 2020-01-21 20:23:39+00:00
2020-01-21 20:10:19,351 botocore.credentials [DEBUG] Credentials need to be refreshed.
2020-01-21 20:10:19,358 botocore.credentials [DEBUG] Retrieved credentials will expire at: 2020-01-21 20:23:39+00:00
...
```

We don't see those exceptions (neither the drop in request count) when using one thread or when using AWS metadata service. What we think is happening is that each process that raises this exception dies and we end up killing the whole application.

What we found as reference is [this issue](https://github.com/boto/boto3/issues/908) that points out that `boto3` was failing because the credentials contain special characters (in the case the `\n` at end of the credential. Look that we have the same `\n` here. Is kube2iam sending incorrect responses?

### Investigating `kube2iam` behaves under this cenario

We were suspecting a race condition or something. However, we found that `ccache` is actually very good at handling concurrent access to the cache and that it should work properly.

![Captura de Tela 2020-01-22 às 12 03 51](https://user-images.githubusercontent.com/1280742/72905474-5cdccf00-3d0f-11ea-8c0e-97867c707e2a.png)

![Captura de Tela 2020-01-22 às 12 05 26](https://user-images.githubusercontent.com/1280742/72905608-91e92180-3d0f-11ea-8ef4-cb56ef99e7cc.png)

![Captura de Tela 2020-01-22 às 12 05 36](https://user-images.githubusercontent.com/1280742/72905617-96add580-3d0f-11ea-8ed6-0db35baffac5.png)

 ### Our conclusion?

We don't know what is happening, but seems to be the way that kube2iam behaves under more heavy load.

**Comment by dsexton** [comment]
@prcastro did you ever come to a resolution for this issue?

**Comment by suessflorian** [comment]
@prcastro, I'm also interested to hear of any resolution.

**Comment by prcastro** [comment]
No resolution yet. We just avoid using multiprocessing for now
