### ISSUE TITLE
cannot assumeRole with java SDK

### ISSUE THREAD

**Issue by rachedanis** [jtblin/kube2iam#271]
## Bug description

Can't assume role using stsClient with anonymous Credentials  

## Current Behavior
```java
Exception in thread "main" com.amazonaws.services.securitytoken.model.AWSSecurityTokenServiceException: Request is missing Authentication Token (Service: AWSSecurityTokenService; Status Code: 403; Error Code: MissingAuthenticationToken; Request ID: idx; Proxy: null)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1811)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1395)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1371)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
        at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.doInvoke(AWSSecurityTokenServiceClient.java:1719)
        at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.invoke(AWSSecurityTokenServiceClient.java:1686)
        at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.invoke(AWSSecurityTokenServiceClient.java:1675)
        at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.executeAssumeRole(AWSSecurityTokenServiceClient.java:589)
        at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.assumeRole(AWSSecurityTokenServiceClient.java:561)
        at mytest.Main.test(Main.java:23)
        at mytest.Main.main(Main.java:36)
```

## Steps to Reproduce

I'm using kubernetes with kube2iam ( that's assuming a role "ROLE-1" ( which is able to assume ROLE-2 ) on my pod  ) ( no need to create an AWS config file )

In my pod I have this Main class :

```java
package mytest;

import com.amazonaws.auth.AWSStaticCredentialsProvider;
import com.amazonaws.auth.AnonymousAWSCredentials;
import com.amazonaws.auth.BasicSessionCredentials;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.cloudformation.AmazonCloudFormation;
import com.amazonaws.services.cloudformation.AmazonCloudFormationClientBuilder;
import com.amazonaws.services.securitytoken.AWSSecurityTokenService;
import com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClientBuilder;
import com.amazonaws.services.securitytoken.model.AssumeRoleRequest;
import com.amazonaws.services.securitytoken.model.AssumeRoleResult;
import com.amazonaws.services.securitytoken.model.Credentials;

public class Main {

    public static void test(String roleArnToAssume, String roleSessionName, Regions region) {
        AWSSecurityTokenService stsClient = AWSSecurityTokenServiceClientBuilder.standard().withCredentials(new AWSStaticCredentialsProvider(new AnonymousAWSCredentials())).withRegion(region).build();

        AssumeRoleRequest roleRequest = new AssumeRoleRequest().withRoleArn(roleArnToAssume)
                .withRoleSessionName(roleSessionName);
        
        AssumeRoleResult assumeRoleResult = stsClient.assumeRole(roleRequest); // Exception here

        Credentials sessionCredentials = assumeRoleResult.getCredentials();
        BasicSessionCredentials awsCredentials = new BasicSessionCredentials(sessionCredentials.getAccessKeyId(),
                sessionCredentials.getSecretAccessKey(), sessionCredentials.getSessionToken());

        AmazonCloudFormation stackbuilder = AmazonCloudFormationClientBuilder.standard()
                .withCredentials(new AWSStaticCredentialsProvider(awsCredentials)).withRegion(region).build();

        System.out.println(stackbuilder);
    }
    public static void main(String[] argv) {
        final Regions region = Regions.EU_WEST_1;
        test("arn:aws:iam::ID:role/ROLE-2", "MySession", region);
    }
}

```

## Context
**Without configuring an aws config** and using boto3 python lib, it's working fine : 
```python
 sts_client = boto3.client(
        "sts"
    )
    assumed_role_object = sts_client.assume_role(
        RoleArn="arn:aws:iam::ID:role/ROLE-1",
        RoleSessionName="MySession",
    )
```

**But using Java SDK it throws the exception above.**

## My Environment
* AWS Java SDK version used: 1.11.775
* JDK version used: 11
* Kube2iam : docker.io/jtblin/kube2iam:0.10.9
* App Pod : softinstigate/maven-aws:latest
* Policies attached to the ROLE-2 : AdministratorAccess
* Role JSON : 
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "sts:AssumeRole",
            "Resource": "*",
            "Effect": "Allow"
        }
    ]
}

```

**Comment by sybeck2k** [comment]
I can confirm that Kube2Iam is not currently supported in Proxy mode by the AWS Java SDK v1 and v2. This is caused by [this piece of code](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/internal/ConnectionUtils.java#L40) - where the call to the metadata service is explicitly set to not use a proxy.
A workaround is to build a custom InstanceProfileCredentialsProvider that uses a custom ConnectionUtils with support for proxies
