### ISSUE TITLE
Release 0.5.1 does not work with Kubernetes 1.6.2

### ISSUE THREAD

**Issue by erickt** [jtblin/kube2iam#66]
It appears that on Kubernetes 1.6.2, release 0.5.1 does not work. It errors with:

```
2017-04-25T04:24:30.461470394Z kube2iam flag redefined: log_dir
2017-04-25T04:24:30.46394961Z panic: kube2iam flag redefined: log_dir
2017-04-25T04:24:30.469260508Z 
2017-04-25T04:24:30.469269816Z goroutine 1 [running]:
2017-04-25T04:24:30.469274018Z flag.(*FlagSet).Var(0xc42000e120, 0x1e59ba0, 0xc420019780, 0x15b7dc5, 0x7, 0x15e26fa, 0x2f)
2017-04-25T04:24:30.469279025Z 	/usr/local/Cellar/go/1.8/libexec/src/flag/flag.go:793 +0x420
2017-04-25T04:24:30.469282795Z flag.(*FlagSet).StringVar(0xc42000e120, 0xc420019780, 0x15b7dc5, 0x7, 0x0, 0x0, 0x15e26fa, 0x2f)
2017-04-25T04:24:30.469285697Z 	/usr/local/Cellar/go/1.8/libexec/src/flag/flag.go:696 +0x8b
2017-04-25T04:24:30.469288735Z flag.(*FlagSet).String(0xc42000e120, 0x15b7dc5, 0x7, 0x0, 0x0, 0x15e26fa, 0x2f, 0xc420019770)
2017-04-25T04:24:30.469291591Z 	/usr/local/Cellar/go/1.8/libexec/src/flag/flag.go:709 +0x90
2017-04-25T04:24:30.469294465Z flag.String(0x15b7dc5, 0x7, 0x0, 0x0, 0x15e26fa, 0x2f, 0x23)
2017-04-25T04:24:30.469297237Z 	/usr/local/Cellar/go/1.8/libexec/src/flag/flag.go:716 +0x69
2017-04-25T04:24:30.469300033Z github.com/jtblin/kube2iam/vendor/k8s.io/client-go/vendor/github.com/golang/glog.init()
2017-04-25T04:24:30.469303218Z 	/Users/jtblin/src/go/src/github.com/jtblin/kube2iam/vendor/k8s.io/client-go/vendor/github.com/golang/glog/glog_file.go:41 +0x14a
2017-04-25T04:24:30.46930643Z github.com/jtblin/kube2iam/vendor/k8s.io/client-go/kubernetes.init()
2017-04-25T04:24:30.46930955Z 	/Users/jtblin/src/go/src/github.com/jtblin/kube2iam/vendor/k8s.io/client-go/kubernetes/import_known_versions.go:42 +0x48
2017-04-25T04:24:30.469312542Z github.com/jtblin/kube2iam/cmd.init()
2017-04-25T04:24:30.46931517Z 	/Users/jtblin/src/go/src/github.com/jtblin/kube2iam/cmd/store.go:161 +0x7d
2017-04-25T04:24:30.469318023Z main.init()
2017-04-25T04:24:30.469322592Z 	/Users/jtblin/src/go/src/github.com/jtblin/kube2iam/main.go:92 +0x53 
```

0.5.0, however, does work. I suspect that #60 is the cause. A quick google came across https://github.com/kubernetes/kubernetes/issues/35096, which suggests using a vendoring tool like Godeps or Glide to flatten out these dependencies. Maybe that would work?

**Comment by jtblin** [comment]
Interesting I'm already using glide and we don't use glog. Will look into
it.

**Comment by hjacobs** [comment]
We have the same problem and can't run release 0.5.1 :disappointed:

**Comment by jtblin** [comment]
Please stick with 0.5.0, might take me a few days to get through that. Will add a warning to release note.

**Comment by jtblin** [comment]
I was able to fix the issue by running `glide install --strip-vendor` as suggested by @mikkeloscar 👍 
I've published the docker image again, given the commit hash didn't change I was able to overwrite the faulty image (for once mutable tags are a good thing).
